# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18eY7zV1t7-zCWc7jochwvpK9OVK9lK9w
"""

def simulador_loja():
    print("🛒 === SIMULADOR DE LOJA ===")
    print("-" * 30)

    # Cadastro de produtos
    produtos = {
        1: {"nome": "Arroz 5kg", "preco": 25.90},
        2: {"nome": "Feijão 1kg", "preco": 8.50},
        3: {"nome": "Macarrão 500g", "preco": 4.20},
        4: {"nome": "Óleo 900ml", "preco": 7.80},
        5: {"nome": "Leite 1L", "preco": 5.30},
        6: {"nome": "Pão de forma", "preco": 6.90}
    }

    carrinho = []
    total = 0

    # Mostrar produtos disponíveis
    print("\n📋 PRODUTOS DISPONÍVEIS:")
    print("ID | Produto          | Preço")
    print("-" * 30)
    for id_produto, info in produtos.items():
        print(f"{id_produto:2d} | {info['nome']:<16} | R$ {info['preco']:>6.2f}")

    # Adicionar itens ao carrinho
    while True:
        try:
            escolha = int(input("\nDigite o ID do produto (0 para finalizar): "))

            if escolha == 0:
                break
            elif escolha in produtos:
                qtd = int(input(f"Quantos {produtos[escolha]['nome']}? "))
                item_total = produtos[escolha]['preco'] * qtd
                carrinho.append({
                    'produto': produtos[escolha]['nome'],
                    'preco_unit': produtos[escolha]['preco'],
                    'quantidade': qtd,
                    'total': item_total
                })
                total += item_total
                print(f"✅ Adicionado: {qtd}x {produtos[escolha]['nome']} - R$ {item_total:.2f}")
            else:
                print("❌ ID inválido!")

        except ValueError:
            print("❌ Digite apenas números!")
        except KeyboardInterrupt:
            print("\n⏹️ Compra cancelada!")
            return

    if total == 0:
        print("🛒 Nenhum item no carrinho!")
        return

    # Mostrar resumo do carrinho
    print("\n🛍️  RESUMO DO CARRINHO:")
    print("-" * 40)
    for item in carrinho:
        print(f"{item['produto']:<20} x{item['quantidade']:2d}  R$ {item['total']:>7.2f}")
    print("-" * 40)
    print(f"{'TOTAL:':<32} R$ {total:>7.2f}")

    # Escolha forma de pagamento
    print("\n💳 FORMA DE PAGAMENTO:")
    print("1 - À VISTA (10% DESCONTO)")
    print("2 - CARTÃO (PREÇO NORMAL)")

    while True:
        try:
            forma_pag = int(input("Escolha (1 ou 2): "))
            if forma_pag in [1, 2]:
                break
            else:
                print("❌ Escolha apenas 1 ou 2!")
        except ValueError:
            print("❌ Digite apenas 1 ou 2!")

    # Calcular valor final
    if forma_pag == 1:
        desconto = total * 0.10
        valor_final = total - desconto
        print(f"\n🎉 PAGAMENTO À VISTA!")
        print(f"Desconto de 10%: -R$ {desconto:.2f}")
        print(f"{'VALOR FINAL:':<32} R$ {valor_final:>7.2f}")
    else:
        valor_final = total
        print(f"\n💳 PAGAMENTO NO CARTÃO!")
        print(f"{'VALOR FINAL:':<32} R$ {valor_final:>7.2f}")

    print("\n✅ OBRIGADO PELA COMPRA! 🛒")
    print("Volte sempre! 👋")

# Executar o simulador
if __name__ == "__main__":
    simulador_loja()